// @flow

/**
 * All redux actions are events
 */

export default {
  TILES_VIEW_LOADED: 'TILES_VIEW_LOADED',
  ITEMS_LOADING: 'ITEMS_LOADING',
  ITEMS_LOADED: 'ITEMS_LOADED',
  ITEMS_LOADING_FAILED: 'ITEMS_LOADING_FAILED',
  ITEM_DETAILS_REQUESTED: 'ITEM_DETAILS_REQUESTED',
  ITEM_DETAILS_RESET: 'ITEM_DETAILS_RESET',
  NAVIGATION_REQUESTED: 'NAVIGATION_REQUESTED'
};
