// flow-typed signature: 6cb40ee73200cfa430df943ef6726516
// flow-typed version: <<STUB>>/react-stonecutter_v^0.3.4/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-stonecutter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-stonecutter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-stonecutter/demo/src/components/App' {
  declare module.exports: any;
}

declare module 'react-stonecutter/demo/src/components/Grid' {
  declare module.exports: any;
}

declare module 'react-stonecutter/demo/src/main' {
  declare module.exports: any;
}

declare module 'react-stonecutter/gulpfile.babel' {
  declare module.exports: any;
}

declare module 'react-stonecutter/lib/react-stonecutter' {
  declare module.exports: any;
}

declare module 'react-stonecutter/src/components/CSSGrid' {
  declare module.exports: any;
}

declare module 'react-stonecutter/src/components/CSSGridItem' {
  declare module.exports: any;
}

declare module 'react-stonecutter/src/components/SpringGrid' {
  declare module.exports: any;
}

declare module 'react-stonecutter/src/enter-exit-styles/foldUp' {
  declare module.exports: any;
}

declare module 'react-stonecutter/src/enter-exit-styles/fromBottom' {
  declare module.exports: any;
}

declare module 'react-stonecutter/src/enter-exit-styles/fromCenter' {
  declare module.exports: any;
}

declare module 'react-stonecutter/src/enter-exit-styles/fromLeftToRight' {
  declare module.exports: any;
}

declare module 'react-stonecutter/src/enter-exit-styles/fromTop' {
  declare module.exports: any;
}

declare module 'react-stonecutter/src/enter-exit-styles/newspaper' {
  declare module.exports: any;
}

declare module 'react-stonecutter/src/enter-exit-styles/simple' {
  declare module.exports: any;
}

declare module 'react-stonecutter/src/enter-exit-styles/skew' {
  declare module.exports: any;
}

declare module 'react-stonecutter/src/higher-order-components/makeResponsive' {
  declare module.exports: any;
}

declare module 'react-stonecutter/src/higher-order-components/measureItems' {
  declare module.exports: any;
}

declare module 'react-stonecutter/src/index' {
  declare module.exports: any;
}

declare module 'react-stonecutter/src/layouts/pinterest' {
  declare module.exports: any;
}

declare module 'react-stonecutter/src/layouts/simple' {
  declare module.exports: any;
}

declare module 'react-stonecutter/src/utils/assertIsElement' {
  declare module.exports: any;
}

declare module 'react-stonecutter/src/utils/commonProps' {
  declare module.exports: any;
}

declare module 'react-stonecutter/src/utils/easings' {
  declare module.exports: any;
}

declare module 'react-stonecutter/src/utils/transformHelpers' {
  declare module.exports: any;
}

declare module 'react-stonecutter/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-stonecutter/demo/src/components/App.jsx' {
  declare module.exports: $Exports<'react-stonecutter/demo/src/components/App'>;
}
declare module 'react-stonecutter/demo/src/components/Grid.jsx' {
  declare module.exports: $Exports<'react-stonecutter/demo/src/components/Grid'>;
}
declare module 'react-stonecutter/demo/src/main.jsx' {
  declare module.exports: $Exports<'react-stonecutter/demo/src/main'>;
}
declare module 'react-stonecutter/gulpfile.babel.js' {
  declare module.exports: $Exports<'react-stonecutter/gulpfile.babel'>;
}
declare module 'react-stonecutter/lib/react-stonecutter.js' {
  declare module.exports: $Exports<'react-stonecutter/lib/react-stonecutter'>;
}
declare module 'react-stonecutter/src/components/CSSGrid.jsx' {
  declare module.exports: $Exports<'react-stonecutter/src/components/CSSGrid'>;
}
declare module 'react-stonecutter/src/components/CSSGridItem.jsx' {
  declare module.exports: $Exports<'react-stonecutter/src/components/CSSGridItem'>;
}
declare module 'react-stonecutter/src/components/SpringGrid.jsx' {
  declare module.exports: $Exports<'react-stonecutter/src/components/SpringGrid'>;
}
declare module 'react-stonecutter/src/enter-exit-styles/foldUp.js' {
  declare module.exports: $Exports<'react-stonecutter/src/enter-exit-styles/foldUp'>;
}
declare module 'react-stonecutter/src/enter-exit-styles/fromBottom.js' {
  declare module.exports: $Exports<'react-stonecutter/src/enter-exit-styles/fromBottom'>;
}
declare module 'react-stonecutter/src/enter-exit-styles/fromCenter.js' {
  declare module.exports: $Exports<'react-stonecutter/src/enter-exit-styles/fromCenter'>;
}
declare module 'react-stonecutter/src/enter-exit-styles/fromLeftToRight.js' {
  declare module.exports: $Exports<'react-stonecutter/src/enter-exit-styles/fromLeftToRight'>;
}
declare module 'react-stonecutter/src/enter-exit-styles/fromTop.js' {
  declare module.exports: $Exports<'react-stonecutter/src/enter-exit-styles/fromTop'>;
}
declare module 'react-stonecutter/src/enter-exit-styles/newspaper.js' {
  declare module.exports: $Exports<'react-stonecutter/src/enter-exit-styles/newspaper'>;
}
declare module 'react-stonecutter/src/enter-exit-styles/simple.js' {
  declare module.exports: $Exports<'react-stonecutter/src/enter-exit-styles/simple'>;
}
declare module 'react-stonecutter/src/enter-exit-styles/skew.js' {
  declare module.exports: $Exports<'react-stonecutter/src/enter-exit-styles/skew'>;
}
declare module 'react-stonecutter/src/higher-order-components/makeResponsive.jsx' {
  declare module.exports: $Exports<'react-stonecutter/src/higher-order-components/makeResponsive'>;
}
declare module 'react-stonecutter/src/higher-order-components/measureItems.jsx' {
  declare module.exports: $Exports<'react-stonecutter/src/higher-order-components/measureItems'>;
}
declare module 'react-stonecutter/src/index.js' {
  declare module.exports: $Exports<'react-stonecutter/src/index'>;
}
declare module 'react-stonecutter/src/layouts/pinterest.js' {
  declare module.exports: $Exports<'react-stonecutter/src/layouts/pinterest'>;
}
declare module 'react-stonecutter/src/layouts/simple.js' {
  declare module.exports: $Exports<'react-stonecutter/src/layouts/simple'>;
}
declare module 'react-stonecutter/src/utils/assertIsElement.js' {
  declare module.exports: $Exports<'react-stonecutter/src/utils/assertIsElement'>;
}
declare module 'react-stonecutter/src/utils/commonProps.js' {
  declare module.exports: $Exports<'react-stonecutter/src/utils/commonProps'>;
}
declare module 'react-stonecutter/src/utils/easings.js' {
  declare module.exports: $Exports<'react-stonecutter/src/utils/easings'>;
}
declare module 'react-stonecutter/src/utils/transformHelpers.js' {
  declare module.exports: $Exports<'react-stonecutter/src/utils/transformHelpers'>;
}
declare module 'react-stonecutter/test/test.jsx' {
  declare module.exports: $Exports<'react-stonecutter/test/test'>;
}
